### ISSUE TITLE
3d graphs

### ISSUE THREAD

**Issue by am2222** [davidmoten/rtree-multi#2]
Hi,
May I ask how do you generate 3d graphs in the readme?

**Comment by davidmoten** [comment]
I used this r script: https://github.com/davidmoten/rtree-3d/blob/master/src/test/r/source.r

**Comment by am2222** [comment]
Hello David,
Thanks,  I really appreciate it. Can I use it to make some plots for my work? With mentioning the source of it?
________________________________

**Comment by davidmoten** [comment]
Oh gosh yes.
