### ISSUE TITLE
Problems with R*-Tree

### ISSUE THREAD

**Issue by guojuntang** [davidmoten/rtree-multi#30]
Hi,

I want to process some multi-dimensional data with R*-tree but some issues occur.

I try to build up the index like this:
```java
RTree<Object, Point> tree = RTree.dimensions(dimension).star().maxChildren(215).<Object, Point>create().add(entries);
```

When the dataset is relatively large with high dimensions (such as 8000 data records with 14 dimensions and 14000 data records with 8 dimensions), it throws an exception.
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Collections.min(Collections.java:636)
	at com.github.davidmoten.rtreemulti.SplitterRStar.split(SplitterRStar.java:66)
	at com.github.davidmoten.rtreemulti.internal.LeafHelper.add(LeafHelper.java:57)
	at com.github.davidmoten.rtreemulti.internal.LeafDefault.add(LeafDefault.java:41)
	at com.github.davidmoten.rtreemulti.internal.NonLeafHelper.add(NonLeafHelper.java:28)
	at com.github.davidmoten.rtreemulti.internal.NonLeafDefault.add(NonLeafDefault.java:38)
	at com.github.davidmoten.rtreemulti.RTree.add(RTree.java:440)
	at com.github.davidmoten.rtreemulti.RTree.add(RTree.java:479)
```
I tried to fix it by increasing the parameter of maxChildren (like set it as 250), but it also throws the same exception.

**Comment by davidmoten** [comment]
thanks for the report, I'll check it out.

**Comment by davidmoten** [comment]
Ok so in some circumstances it appears that `pairs` never gets set (and is null). This will take a bit of a think.

https://github.com/davidmoten/rtree-multi/blob/1dc63ff505d08cb8ae6e207c5a8c06983e69e630/src/main/java/com/github/davidmoten/rtreemulti/SplitterRStar.java#L35-L67

**Comment by davidmoten** [comment]
Given the path taken to the NPE, the items list passed to the split method must be non-empty so the only ways we can get a null `pairs` variable is if 
* `marginSum == Float.MAX_VALUE` (unlikely)
* or, one of your items is reporting 0 dimensions. Is that a possibility?

Given that I don't have your data to experiment with can you do a bit more research as to the cause, or supply me with a failing unit test?

**Comment by davidmoten** [comment]
A defensive approach would be to change the check `if (marginSum < lowestMarginSum)` to `if (marginSum <=lowestMarginSum)` but it seem unlikely to be the cause.

**Comment by guojuntang** [comment]
@davidmoten Thank you Dave.

I wrote a simple case with my dataset:
```java
import com.github.davidmoten.rtreemulti.Entry;
import com.github.davidmoten.rtreemulti.RTree;
import com.github.davidmoten.rtreemulti.geometry.Point;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

public class Test {
    private static String filename = "/EEGEyeState.csv";
    private static int data_dimension = 14;
    private static int data_number = 10000;
    private static List<double[]> dataset;
    /**
     *
     * @param filename
     * @param d data dimensions
     * @param n data number
     * @return
     */
    public static List<double[]> readCsvData(String filename,int d, int n){
        try {
            List<double[]> result = new ArrayList<>();
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(Test.class.getResourceAsStream(filename)));
            String line;
            String[] string_buffer;
            for (int i = 0; i < n; i++) {
                line = bufferedReader.readLine();
                string_buffer = line.split(",");
                if(d > string_buffer.length){
                    throw new Exception("Data dimension is out of range");
                }
                double[] tmp = new double[d];
                for (int j = 0; j < d; j++) {
                    tmp[j] = Double.valueOf(string_buffer[j]);
                }
                result.add(tmp);

            }
            return result;
        }catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }

    public static void main(String[] args) {
        dataset = readCsvData(filename, data_dimension, data_number);
        RTree<double[], Point> tree = RTree.dimensions(data_dimension).star().maxChildren(200).create();
        for (int i = 0; i < dataset.size(); i++) {
            double[] a = dataset.get(i);
            try{
                tree = tree.add(Entry.entry(a, Point.create(a)));
            }catch (Exception e){
                System.out.println(i);
                e.printStackTrace();
                return;
            }
        }

    }
}

```

[EEGEyeState.csv](https://github.com/davidmoten/rtree-multi/files/8694230/EEGEyeState.csv)

And then I found that it will throw the exception at the circumstance you mentioned.

When I tried to use a debugger, it showed the marginSum was always equal to Infinity at the fail case.

And it seems to be ok when I fix it with double type:

```java
    @Override
    public <T extends HasGeometry> ListPair<T> split(List<T> items, int minSize) {
        Preconditions.checkArgument(!items.isEmpty());
        // sort nodes into increasing x, calculate min overlap where both groups
        // have more than minChildren

        // compute S the sum of all margin-values of the lists above
        // the list with the least S is then used to find minimum overlap

        List<ListPair<T>> pairs = null;
        //float lowestMarginSum = Float.MAX_VALUE;
        double lowestMarginSum = Double.MAX_VALUE;
        List<T> list = null;
        for (int i = 0; i < items.get(0).geometry().dimensions(); i++) {
            for (boolean isUpper : BOOLEANS) {
                if (list == null) {
                    list = new ArrayList<T>(items);
                }
                Collections.sort(list, comparator(i, isUpper));
                List<ListPair<T>> p = getPairs(minSize, list);
                double marginSum = marginValueSum(p);
                if (marginSum < lowestMarginSum) {
                    lowestMarginSum = marginSum;
                    pairs = p;
                    // because p uses subViews of list we need to create a new one
                    // for further comparisons
                    list = null;
                }
            }
        }
        return Collections.min(pairs, comparator);
    }
```

**Comment by davidmoten** [comment]
@guojuntang Thanks very much for investigating! I'll apply the fix you mention shortly.

**Comment by davidmoten** [comment]
Would you like to make a PR with the fix? I can do it but as you did the hard work you get the credit in the project history.

**Comment by davidmoten** [comment]
I'm not fussed in this case about an accompanying test case, just make the change to SplitterRTree as you described.

**Comment by davidmoten** [comment]
I think we should defensively also use `marginSum <= lowestMarginSum` and start with a value of `Double.POSITIVE_INFINITY` as well.

**Comment by guojuntang** [comment]
My pleasure!

I created a PR, and I also check it with executing the unit tests.

BTW,  I am working on my paper with your code. Once finished I will add this repo to the reference list.

**Comment by davidmoten** [comment]
Thanks for the report and the fix. 0.1 is on Maven Central now (for download, won't appear in the index for 24 hours or so).

I'll be interested to hear how you go indexing multiple dimensions with an R-Tree. The literature that I've come across favours a hilbert-index over an R-tree for larger numbers of dimensions. I've got a good hilbert-index library at https://github.com/davidmoten/hilbert-index.
